import { ChangeEvent, FormEvent, useState } from "react";
import { ArrowLeft, BookOpen, ChevronLeft, ChevronRight, Image as ImageIcon, ImagePlus, Pencil, Plus, RotateCcw, Save, Trash2, Users, Megaphone, Phone, BarChart3, Quote, FileText } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { defaultSiteData, readSiteData, resetSiteData, saveSiteData, type Announcement, type ContactDetails, type GalleryItem, type HeroStat, type SiteData, type Subject, type Teacher, type Testimonial, type StudyMaterial } from "@/lib/siteData";

type Tab = "subjects" | "teachers" | "gallery" | "stats" | "testimonials" | "announcements" | "contact" | "papers" | "unitQuestions";
const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
const emptySubject: Subject = { id: "", subject: "", batch: "", schedule: "", seats: "" };
const emptyTeacher: Teacher = { id: "", name: "", subject: "", bio: "", image: "" };
const emptyGallery: GalleryItem = { id: "", image: "", alt: "", layout: "standard" };
const emptyStat: HeroStat = { id: "", value: "", label: "" };
const emptyTestimonial: Testimonial = { id: "", quote: "", attribution: "" };
const emptyAnnouncement: Announcement = { id: "", title: "", description: "", date: "", target: "All families" };
const emptyContact: ContactDetails = { address: "", phone: "", email: "", hours: "" };
const emptyPaper: StudyMaterial = { id: "", title: "", subject: "", link: "", type: "paper" };
const emptyUnitQuestion: StudyMaterial = { id: "", title: "", subject: "", link: "", type: "unit" };

const tabMeta: Record<Tab, { label: string; icon: typeof BookOpen }> = { subjects: { label: "Subjects & batches", icon: BookOpen }, teachers: { label: "Teachers & staff", icon: Users }, gallery: { label: "Classroom gallery", icon: ImageIcon }, stats: { label: "Hero statistics", icon: BarChart3 }, testimonials: { label: "Parent notes", icon: Quote }, announcements: { label: "Announcements", icon: Megaphone }, contact: { label: "Contact details", icon: Phone }, papers: { label: "Question papers", icon: FileText }, unitQuestions: { label: "Unit questions", icon: FileText } };

export default function Admin() {
  const [data, setData] = useState<SiteData>(() => readSiteData());
  const [tab, setTab] = useState<Tab>("subjects");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [subject, setSubject] = useState(emptySubject); const [teacher, setTeacher] = useState(emptyTeacher); const [gallery, setGallery] = useState(emptyGallery); const [stat, setStat] = useState(emptyStat); const [testimonial, setTestimonial] = useState(emptyTestimonial); const [announcement, setAnnouncement] = useState(emptyAnnouncement); const [contact, setContact] = useState(emptyContact); const [paper, setPaper] = useState(emptyPaper); const [unitQuestion, setUnitQuestion] = useState(emptyUnitQuestion);
  const [preview, setPreview] = useState(true); const [previewTestimonial, setPreviewTestimonial] = useState(0);

  const commit = (next: SiteData, message: string) => { setData(next); saveSiteData(next); toast.success(message); };
  const clearForm = () => { setEditingId(null); setSubject(emptySubject); setTeacher(emptyTeacher); setGallery(emptyGallery); setStat(emptyStat); setTestimonial(emptyTestimonial); setAnnouncement(emptyAnnouncement); setContact(emptyContact); setPaper(emptyPaper); setUnitQuestion(emptyUnitQuestion); };
  const selectTab = (next: Tab) => { setTab(next); clearForm(); };
  const edit = (item: any) => { setEditingId(item.id); if (tab === "subjects") setSubject({ ...item }); if (tab === "teachers") setTeacher({ ...item }); if (tab === "gallery") setGallery({ ...item }); if (tab === "stats") setStat({ ...item }); if (tab === "testimonials") setTestimonial({ ...item }); if (tab === "announcements") setAnnouncement({ ...item }); if (tab === "papers") setPaper({ ...item }); if (tab === "unitQuestions") setUnitQuestion({ ...item }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const remove = (key: keyof Pick<SiteData, "subjects" | "teachers" | "gallery" | "heroStats" | "testimonials" | "announcements" | "questionPapers" | "unitQuestions">, itemId: string) => { commit({ ...data, [key]: data[key].filter((entry: any) => entry.id !== itemId) } as SiteData, "Item deleted"); if (editingId === itemId) clearForm(); };
  const saveListItem = (event: FormEvent, key: "subjects" | "teachers" | "gallery" | "heroStats" | "testimonials" | "announcements" | "questionPapers" | "unitQuestions", value: any, label: string) => { event.preventDefault(); const item = { ...value, id: value.id || id(key.slice(0, -1)) }; if (Object.entries(item).some(([field, entry]) => field !== "id" && field !== "type" && !String(entry).trim())) return toast.error("Please complete every field"); const list = data[key] as any[]; const nextList = editingId ? list.map((entry) => entry.id === editingId ? item : entry) : [...list, item]; commit({ ...data, [key]: nextList }, editingId ? `${label} updated` : `${label} added`); clearForm(); };
  const saveContact = (event: FormEvent) => { event.preventDefault(); if (!contact.address || !contact.phone || !contact.email || !contact.hours) return toast.error("Please complete every contact field"); commit({ ...data, contact }, "Contact details updated"); };
  const upload = (event: ChangeEvent<HTMLInputElement>, callback: (value: string) => void) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) return toast.error("Choose an image file"); if (file.size > 3 * 1024 * 1024) return toast.error("Keep images below 3 MB"); const reader = new FileReader(); reader.onload = () => callback(String(reader.result)); reader.readAsDataURL(file); };
  const restore = () => { resetSiteData(); setData(defaultSiteData); clearForm(); toast.success("Demo content restored"); };
  const count = data.subjects.length + data.teachers.length + data.gallery.length + data.heroStats.length + data.testimonials.length + data.announcements.length + data.questionPapers.length + data.unitQuestions.length;
  const previewNote = data.testimonials[previewTestimonial % Math.max(data.testimonials.length, 1)];

  const renderForm = () => {
    if (tab === "subjects") return <form className="admin-form" onSubmit={(e) => saveListItem(e, "subjects", subject, "Subject")}><Field label="Subject name" value={subject.subject} onChange={(v) => setSubject({ ...subject, subject: v })} placeholder="Tamil" /><Field label="Grade / batch" value={subject.batch} onChange={(v) => setSubject({ ...subject, batch: v })} placeholder="Grades 6–8 · Core" /><Field label="Schedule" value={subject.schedule} onChange={(v) => setSubject({ ...subject, schedule: v })} placeholder="Mon / Wed · 4:30 PM" /><Field label="Seats available" value={subject.seats} onChange={(v) => setSubject({ ...subject, seats: v })} placeholder="06 seats" /><SaveButton editing={!!editingId} label="subject" /></form>;
    if (tab === "teachers") return <form className="admin-form" onSubmit={(e) => saveListItem(e, "teachers", teacher, "Teacher")}><Field label="Teacher / staff name" value={teacher.name} onChange={(v) => setTeacher({ ...teacher, name: v })} placeholder="Priya Iyer" /><Field label="Subject or role" value={teacher.subject} onChange={(v) => setTeacher({ ...teacher, subject: v })} placeholder="Tamil" /><TextField label="Short bio" value={teacher.bio} onChange={(v) => setTeacher({ ...teacher, bio: v })} placeholder="A short introduction..." /><Field label="Photo URL" value={teacher.image} onChange={(v) => setTeacher({ ...teacher, image: v })} placeholder="https://..." /><Upload label="Or upload a staff photo" onFile={(value) => setTeacher({ ...teacher, image: value })} />{teacher.image && <img className="admin-image-preview" src={teacher.image} alt="Preview" />}<SaveButton editing={!!editingId} label="teacher" /></form>;
    if (tab === "gallery") return <form className="admin-form" onSubmit={(e) => saveListItem(e, "gallery", gallery, "Gallery image")}><Field label="Image URL" value={gallery.image} onChange={(v) => setGallery({ ...gallery, image: v })} placeholder="https://..." /><Upload label="Or upload classroom image" onFile={(value) => setGallery({ ...gallery, image: value })} />{gallery.image && <img className="admin-image-preview" src={gallery.image} alt="Preview" />}<Field label="Image description" value={gallery.alt} onChange={(v) => setGallery({ ...gallery, alt: v })} placeholder="Students working together" /><SelectField label="Gallery layout" value={gallery.layout} onChange={(v) => setGallery({ ...gallery, layout: v as GalleryItem["layout"] })} options={["standard", "wide", "tall"]} /><SaveButton editing={!!editingId} label="image" /></form>;
    if (tab === "stats") return <form className="admin-form" onSubmit={(e) => saveListItem(e, "heroStats", stat, "Hero statistic")}><Field label="Value" value={stat.value} onChange={(v) => setStat({ ...stat, value: v })} placeholder="12" /><Field label="Label" value={stat.label} onChange={(v) => setStat({ ...stat, label: v })} placeholder="Batches running" /><SaveButton editing={!!editingId} label="statistic" /></form>;
    if (tab === "testimonials") return <form className="admin-form" onSubmit={(e) => saveListItem(e, "testimonials", testimonial, "Parent note")}><TextField label="Parent quote" value={testimonial.quote} onChange={(v) => setTestimonial({ ...testimonial, quote: v })} placeholder="The biggest change was..." /><Field label="Attribution" value={testimonial.attribution} onChange={(v) => setTestimonial({ ...testimonial, attribution: v })} placeholder="Meera S., parent of Ananya · Grade 10" /><SaveButton editing={!!editingId} label="parent note" /></form>;
    if (tab === "announcements") return <form className="admin-form" onSubmit={(e) => saveListItem(e, "announcements", announcement, "Announcement")}><Field label="Announcement title" value={announcement.title} onChange={(v) => setAnnouncement({ ...announcement, title: v })} placeholder="New batches are open" /><TextField label="Description" value={announcement.description} onChange={(v) => setAnnouncement({ ...announcement, description: v })} placeholder="Book a free conversation..." /><Field label="Date" value={announcement.date} onChange={(v) => setAnnouncement({ ...announcement, date: v })} placeholder="2024-06-01" /><Field label="Audience" value={announcement.target} onChange={(v) => setAnnouncement({ ...announcement, target: v })} placeholder="All families" /><SaveButton editing={!!editingId} label="announcement" /></form>;
    if (tab === "papers") return <form className="admin-form" onSubmit={(e) => saveListItem(e, "questionPapers", paper, "Question paper")}><Field label="Paper title" value={paper.title} onChange={(v) => setPaper({ ...paper, title: v })} placeholder="Mathematics Mid-Term 2026" /><Field label="Subject" value={paper.subject} onChange={(v) => setPaper({ ...paper, subject: v })} placeholder="Mathematics" /><Field label="Document Link (Google Drive / URL)" value={paper.link} onChange={(v) => setPaper({ ...paper, link: v })} placeholder="https://..." /><SaveButton editing={!!editingId} label="question paper" /></form>;
    if (tab === "unitQuestions") return <form className="admin-form" onSubmit={(e) => saveListItem(e, "unitQuestions", unitQuestion, "Unit question")}><Field label="Unit / Topic title" value={unitQuestion.title} onChange={(v) => setUnitQuestion({ ...unitQuestion, title: v })} placeholder="Algebra and equations" /><Field label="Subject" value={unitQuestion.subject} onChange={(v) => setUnitQuestion({ ...unitQuestion, subject: v })} placeholder="Mathematics" /><Field label="Document Link (Google Drive / URL)" value={unitQuestion.link} onChange={(v) => setUnitQuestion({ ...unitQuestion, link: v })} placeholder="https://..." /><SaveButton editing={!!editingId} label="unit question" /></form>;
    return <form className="admin-form" onSubmit={saveContact}><TextField label="Address" value={contact.address || data.contact.address} onChange={(v) => setContact({ ...data.contact, address: v })} placeholder="24, 12th Main\nIndiranagar, Bengaluru" /><Field label="Phone" value={contact.phone || data.contact.phone} onChange={(v) => setContact({ ...data.contact, phone: v })} placeholder="+91 80 1234 5678" /><Field label="Email" value={contact.email || data.contact.email} onChange={(v) => setContact({ ...data.contact, email: v })} placeholder="hello@thestudyroom.in" /><Field label="Opening hours" value={contact.hours || data.contact.hours} onChange={(v) => setContact({ ...data.contact, hours: v })} placeholder="Mon–Sat · 9:00 AM–7:00 PM" /><SaveButton editing label="contact details" /></form>;
  };

  const renderList = () => { const key = tab === "stats" ? "heroStats" : tab === "papers" ? "questionPapers" : tab; if (tab === "contact") return <div className="contact-preview-card"><strong>{data.contact.email}</strong><span>{data.contact.phone}</span><span>{data.contact.hours}</span><span>{data.contact.address}</span></div>; const list = data[key as keyof SiteData] as any[]; return <div className="admin-list">{list.map((item) => <div className="admin-list-item" key={item.id}>{tab === "teachers" || tab === "gallery" ? <img className="list-thumb" src={item.image} alt="" /> : <div className="list-icon"><IconFor tab={tab} /></div>}<div className="list-copy"><strong>{item.name || item.subject || item.value || item.title || item.quote}</strong><span>{item.batch || item.schedule || item.label || item.attribution || item.description || item.layout || item.subject}</span></div><div className="list-actions"><button onClick={() => edit(item)} aria-label="Edit"><Pencil size={15} /></button><button onClick={() => remove(key as any, item.id)} aria-label="Delete"><Trash2 size={15} /></button></div></div>)}</div>; };

  return <div className="admin-shell"><header className="admin-header"><div className="admin-header-inner"><Link href="/" className="admin-brand"><span className="brand-mark">RM</span><span><b>Rasi Maths Tuition Centre</b><small>Portfolio content manager</small></span></Link><div className="admin-header-actions"><span className="admin-status"><i /> Local draft mode</span><Link href="/" className="admin-view-link"><ArrowLeft size={15} /> View portfolio</Link></div></div></header><main className="admin-main page-width"><div className="admin-intro"><div><p className="eyebrow">Admin / Content editor</p><h1>Keep the story<br /><em>up to date.</em></h1><p>Every field below supports CRUD. Toggle live preview to see unsaved edits on the right before saving them to the public page.</p></div><div className="admin-summary"><strong>{count}</strong><span>editable content items</span></div></div><div className="admin-tabs" role="tablist">{(Object.keys(tabMeta) as Tab[]).map((key) => { const Meta = tabMeta[key]; const Icon = Meta.icon; const length = key === "stats" ? data.heroStats.length : key === "contact" ? 1 : (data[key] as any[]).length; return <button key={key} className={tab === key ? "is-active" : ""} onClick={() => selectTab(key)}><Icon size={16} /> {Meta.label} <b>{length}</b></button>; })}</div><div className="preview-toggle-row"><span><span className="live-dot" /> Live preview updates as you type</span><button className={`preview-toggle ${preview ? "is-on" : ""}`} onClick={() => setPreview(!preview)}>{preview ? "Preview on" : "Preview off"}</button></div><section className={`admin-workspace ${preview ? "with-preview" : ""}`}><div className="admin-form-panel"><div className="admin-panel-heading"><div><span className="admin-kicker">{editingId ? "Update existing" : "Create new"}</span><h2>{editingId ? "Edit item" : `Add ${tabMeta[tab].label.toLowerCase()}`}</h2></div>{editingId && <button className="text-button" onClick={clearForm}>Cancel edit</button>}</div>{renderForm()}</div><div className="admin-list-panel"><div className="admin-panel-heading"><div><span className="admin-kicker">Published items</span><h2>{tabMeta[tab].label}</h2></div>{tab !== "contact" && <button className="admin-add-button" onClick={clearForm}><Plus size={16} /> New</button>}</div>{renderList()}</div>{preview && <Preview data={data} tab={tab} subject={subject} teacher={teacher} gallery={gallery} stat={stat} testimonial={testimonial} announcement={announcement} contact={contact} />}</section><div className="admin-footer-actions"><button className="reset-button" onClick={restore}><RotateCcw size={15} /> Restore demo content</button><span><Save size={14} /> Saved locally in this browser · public page updates after save</span></div></main></div>;
}

function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (v: string) => void; placeholder?: string }) { return <label>{label}<input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} /></label>; }
function TextField({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (v: string) => void; placeholder?: string }) { return <label>{label}<textarea value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} rows={4} /></label>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: string[] }) { return <label>{label}<select value={value} onChange={(e) => onChange(e.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function Upload({ label, onFile }: { label: string; onFile: (value: string) => void }) { return <label className="upload-box"><ImagePlus size={18} /><span><b>{label}</b><small>JPG or PNG · max 3 MB · stored in this browser</small></span><input type="file" accept="image/*" onChange={(e) => { const file = e.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => onFile(String(reader.result)); reader.readAsDataURL(file); }} /></label>; }
function SaveButton({ editing, label }: { editing: boolean; label: string }) { return <button className="admin-save-button" type="submit"><Save size={16} /> {editing ? `Save ${label}` : `Add ${label}`}</button>; }
function IconFor({ tab }: { tab: Tab }) { const Icon = tab === "testimonials" ? Quote : tab === "announcements" ? Megaphone : tab === "stats" ? BarChart3 : (tab === "papers" || tab === "unitQuestions") ? BookOpen : BookOpen; return <Icon size={17} />; }

function Preview({ data, tab, subject, teacher, gallery, stat, testimonial, announcement, contact, paper, unitQuestion }: { data: SiteData; tab: Tab; subject: Subject; teacher: Teacher; gallery: GalleryItem; stat: HeroStat; testimonial: Testimonial; announcement: Announcement; contact: ContactDetails; paper: StudyMaterial; unitQuestion: StudyMaterial }) {
  const hasValue = (item: any) => Object.entries(item).some(([key, value]) => key !== "id" && key !== "type" && String(value).trim());
  return <aside className="live-preview"><div className="live-preview-top"><span><i /> LIVE PREVIEW</span><small>Unsaved changes shown</small></div>{tab === "subjects" && <div className="preview-subject"><p>Subjects / Timetable</p><h3>{subject.subject || "Your new subject"}</h3><span>{subject.batch || "Grade / batch"}</span><span>{subject.schedule || "Schedule"}</span><b>{subject.seats || "Seats"}</b></div>}{tab === "teachers" && <div className="preview-teacher">{teacher.image && <img src={teacher.image} alt="" />}<p>Teacher card</p><h3>{teacher.name || "New teacher"}</h3><b>{teacher.subject || "Subject or role"}</b><span>{teacher.bio || "Your teacher bio will appear here."}</span></div>}{tab === "gallery" && <div className="preview-gallery">{gallery.image ? <img src={gallery.image} alt="" /> : <div className="preview-empty"><ImageIcon size={25} /><span>Upload an image to preview it</span></div>}<p>{gallery.alt || "Image description"}</p></div>}{tab === "stats" && <div className="preview-stat"><span>{stat.value || "00"}</span><p>{stat.label || "Your statistic label"}</p></div>}{tab === "testimonials" && <div className="preview-note"><p>05 / A parent’s note</p><blockquote>“{testimonial.quote || "Your parent note will appear here."}”</blockquote><span>— {testimonial.attribution || "Attribution"}</span></div>}{tab === "announcements" && <div className="preview-announcement"><p>Announcement banner</p><h3>{announcement.title || "Your announcement title"}</h3><span>{announcement.description || "Your announcement description"}</span></div>}{tab === "contact" && <div className="preview-contact"><p>Contact / CTA strip</p><h3>Let’s find the<br /><em>right next step.</em></h3><span>{contact.address || data.contact.address}</span><span>{contact.phone || data.contact.phone}</span><span>{contact.email || data.contact.email}</span><span>{contact.hours || data.contact.hours}</span></div>}{(tab === "papers" || tab === "unitQuestions") && <div className="preview-subject"><p>{tab === "papers" ? "Question paper link" : "Unit question link"}</p><h3>{tab === "papers" ? (paper.title || "New Paper") : (unitQuestion.title || "New Topic")}</h3><span>{tab === "papers" ? (paper.subject || "Subject") : (unitQuestion.subject || "Subject")}</span><b className="break-all">{tab === "papers" ? (paper.link || "Link will appear here") : (unitQuestion.link || "Link will appear here")}</b></div>}{!hasValue(tab === "subjects" ? subject : tab === "teachers" ? teacher : tab === "gallery" ? gallery : tab === "stats" ? stat : tab === "testimonials" ? testimonial : tab === "announcements" ? announcement : tab === "papers" ? paper : tab === "unitQuestions" ? unitQuestion : contact) && <div className="preview-hint">Start typing to see your draft here before saving.</div>}</aside>;
}
